app = 'sladify'
primary_region = 'nrt'

[[mounts]]
  source = 'sladify_data'
  destination = '/data'

[processes]
  app = "sh -c 'npx prisma migrate deploy; exec node dist/index.js'"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
